spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
      client:
        registration:
          task-tracker-oidc:
            provider: spring
            client-id: task-tracker
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://client-server:8090/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: task-tracker-oidc
          task-tracker-authorization-code:
            provider: spring
            client-id: task-tracker
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://client-server:8090/authorized"
            scope: task.read
            client-name: task-tracker-authorization-code
        provider:
          spring:
            issuer-uri: http://auth-server:9000

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        validator:
          apply_to_ddl: false
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: test
    password: test


  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      auto-offset-reset: earliest
      group-id: task-tracker
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    admin:
      auto-create: true
    bootstrap-servers:
      - localhost:9092
    properties:
      security.protocol: PLAINTEXT
      schema.registry.url: http://localhost:8083
      specific.avro.reader: true
    topics:
      users-registered: users.registered
      task-cud-streaming: tasks.changes.streaming
      task-workflow-events: tasks.workflow

server:
  port: 8090
#  servlet:
#    context-path: "/task-tracker/api"

logging:
  level:
    org.springframework.security: trace