spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
      client:
        registration:
          task-tracker-oidc:
            provider: spring
            client-id: task-tracker
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://client-server:8090/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: task-tracker-oidc
          task-tracker-authorization-code:
            provider: spring
            client-id: task-tracker
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://client-server:8090/authorized"
            scope: task.read
            client-name: task-tracker-authorization-code
        provider:
          spring:
            issuer-uri: http://auth-server:9000

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        validator:
          apply_to_ddl: false
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: test
    password: test


  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      group-id: task-tracker
      properties:
        spring.json.trusted.packages: ru.denisqq.asyncarch.tasktracker.kafka.UsersBeConsumer.UserRegisteredEvent
    producer:
      acks: all
    admin:
      auto-create: true
    bootstrap-servers:
      - localhost:9092
    properties:
      security.protocol: PLAINTEXT
    topics:
      users-be: users.business.events
      destination-map:
        task-cud-streaming: tasks.changes.streaming
        task-be-events: tasks.business.events

server:
  port: 8090
#  servlet:
#    context-path: "/task-tracker/api"

logging:
  level:
    org.springframework.security: trace